// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	models "github.com/bonifacio/todogo/models"
	mock "github.com/stretchr/testify/mock"
)

// TodoService is an autogenerated mock type for the TodoService type
type TodoService struct {
	mock.Mock
}

// Create provides a mock function with given fields: todo
func (_m *TodoService) Create(todo models.Todo) *models.Todo {
	ret := _m.Called(todo)

	var r0 *models.Todo
	if rf, ok := ret.Get(0).(func(models.Todo) *models.Todo); ok {
		r0 = rf(todo)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Todo)
		}
	}

	return r0
}

type mockConstructorTestingTNewTodoService interface {
	mock.TestingT
	Cleanup(func())
}

// NewTodoService creates a new instance of TodoService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewTodoService(t mockConstructorTestingTNewTodoService) *TodoService {
	mock := &TodoService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
